image: Ubuntu

configuration: Release

build:
  verbosity: minimal
  publish_aspnet_core: true

deploy:
  provider: WebDeploy
  server:
  website:
  username:
  password:
  ntlm: false
  remove_files: false
