image: Ubuntu

configuration: Release

build:
  publish_aspnet_core: true
  verbosity: minimal

artifacts:
  - path: bin\$(configuration)\*.dll
    type: WebDeployPackage

deploy:
  provider: WebDeploy
  server:
  website:
  username:
  password:
  ntlm: false
  remove_files: false
