image: Ubuntu

configuration: Release

build:
  publish_aspnet_core: true
  verbosity: minimal

artifacts:
  - path: /home/appveyor/projects/todo-kata/ApiIntegrationKata/bin/Release/net5.0\*
    type: WebDeployPackage

deploy:
  provider: WebDeploy
  server:
  website:
  username:
  password:
  ntlm: false
  remove_files: false
