image: Ubuntu

configuration: Release

build:
  publish_aspnet_core: true
  verbosity: minimal

artifacts:
  - path: test.zip

deploy:
  provider: WebDeploy
  server:
  website:
  username:
  password:
  ntlm: false
  remove_files: false
  artifact: test.zip
